### ISSUE TITLE
Small files request

### ISSUE THREAD

**Issue by adelomana** [tgen/MMRF_CoMMpass#4]
Hi!

I'm trying to add some RNAseq samples to the "MMRF_CoMMpass_IA14a_E74GTF_Salmon_V7.2_Filtered_Gene_TPM.txt" file. I generated the appropriate GTF and fa files as explained in the "MMRF_CoMMpass_IA14_Methods.pdf" documentation (thanks for that, very helpful!).

I'm in the last step on page 32, and there are a couple of commands to filter some transcripts and map ENST to ENSG. But it seems there are two files that I can't find: $​{​ENST_TO_FILTER​} and $​{​ENSG_TO_ENST_MAP​}. Would it be possible to share those files or to explain how to generate them? That would be awesome.

Thanks so much for your help!

Adrian.

**Comment by awchrist** [comment]
Hi @adelomana,

I just added them to the "immunoglobulin_transcripts" folder. Please use the "Homo_sapiens_GRCh37_74_ig_ENST_to_filter_out.tsv" for the ${ENST_TO_FILTER} variable and "Homo_sapiens_GRCh37_74_ENSG_to_ENST_map.txt" for the ${ENSG_TO_ENST_MAP} variable.

Let us know if you have any additional question or run into any hiccups.

**Comment by adelomana** [comment]
wow, thanks so much for your quick response! It works perfectly now. Thanks for providing such a detailed and easy-to-follow documentation. Cheers!
