### ISSUE TITLE
make_ref_genome_and_gtf.sh does not run

### ISSUE THREAD

**Issue by khughitt** [tgen/MMRF_CoMMpass#5]
Greetings!

In attempting to use the `make_ref_genome_and_gtf.sh` script to recreate the reference genome use to map CoMMpass reads, I noticed a few issues with the script:

1. Typo on line 127 (comma instead of semicolon):

```
for ( i = 1 , i <= n ; i++ ) 
```

Should be:

```
for ( i = 1 ; i <= n ; i++ ) 
```

2. The URL for the ERCC has changed and now both the fasta file and gtf file are available through a single zip archive:

```
wget https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip
unzip ERCC92.zip
```

3. The `awk` command on line 116 generates an empty output file.

I spent a little bit of time trying to fix the last issue, but haven't had any luck so far. Because of this, I also have not been able to test the final awk command in the script.

Any ideas what the issue could be there?

**Comment by johnsquilinda** [comment]
How do I unsubscribe? I’ve tried a few times over the years.

**Comment by PedalheadPHX** [comment]
HI Keith,

Hope things are going well for you.  I'll have someone on the team look into the issues, and update the ERCC path information.

**Comment by PedalheadPHX** [comment]
> How do I unsubscribe? I’ve tried a few times over the years.
> […](#)
> On Apr 14, 2020, at 6:13 AM, Keith Hughitt ***@***.***> wrote: command

@johnsquilinda I think you can unsubscribe with the button on the right hand side under notifications, that might just be this issue thread, you can also change your notification settings under the UNWATCH button at the top of the page

**Comment by khughitt** [comment]
@PedalheadPHX Thanks, Jonathan! Take care and stay safe.

**Comment by awchrist** [comment]
@khughitt I updated the script to use the link for the ERCC92.zip, fixed the awk command that was using a comma and I believe the reason the awk steps are not working is because on our system awk == gawk. I've update the script to use gawk instead but you will need to double check if you have gawk installed on your system.

**Comment by khughitt** [comment]
@awchrist One more quick question -- In the CoMMpass methods documentation describing the approach used for reference generation and transcript abundance quantification (`MMRF_CoMMpass_IA14_Methods.pdf`), it's suggested that `make_ref_genome_and_gtf.sh` handles generation of the reference transcriptome used by Salmon, etc.

Unless I am missing something, however, it looks like `make_ref_genome_and_gtf.sh` generates a modified reference _genome_, but no _transcriptome_.

Is there anywhere that describes the specific steps used to generate the transcriptome needed by Salmon?

Thanks!

**Comment by PedalheadPHX** [comment]
I'm sure its in a readme on the server but todays best practice is in our new pipeline build scripts (https://github.com/tgen/jetstream_resources/blob/master/utility_scripts/create_transcript_fasta.sh)

**Comment by khughitt** [comment]
@PedalheadPHX Great! Thanks again, Jonathan.

Out of curiosity, before I spend too much time working on something that you may have already done yourselves, I don't suppose you have ever reprocessed the HMCL RNA-Seq data using the reference / methods used in MMRF, have you?

Sarin et al., published [a nice comparison of the two datasets](https://www.nature.com/articles/s41375-020-0785-1) last month, however, they did the comparison using the processed versions of the datasets.

I was thinking it would be interesting to do a similar kind of analysis, but first re-doing the quantification for one or both of the datasets to reduce the impact of differences in those early processing steps. I'm also considering using something like ComBat to try and adjust for experimental differences, although I think that will only really be useful If I can incorporate some additional datasets; otherwise, "experiment" and "cell line vs. patient" would be completely confounded.

**Comment by PedalheadPHX** [comment]
We have pushed all the cell lines though the same pipeline as the MMRF IA1-16 releases that used out old pipeline.  The cell lines are ran as tumor only but the RNA data would be a straight comparison

**Comment by khughitt** [comment]
Okay great! That simplifies things a lot. Is that data available online anywhere, or would it be possible to get a copy? I did not see a link anywhere on the [HMCL data repository](https://www.keatslab.org/data-repository).
