### ISSUE TITLE
GTF based Salmon index

### ISSUE THREAD

**Issue by parvathisudha** [tgen/MMRF_CoMMpass#6]
Hi, 

Can you please explain how you generate the GTF based index for Salmon? 

To create the Salmon index, I used transcript.fa. 
`salmon index -t /salmon/GRCh38/gencode.v35.pc_transcripts.fa -i /salmon/GRCh38/salmon_index --type quasi -k 31 --gencode`
When did the quantification based on this index, even after having GTF using -g option, the "quant.genes.sf" is only showing the Transcript id's not gene id's. 
So, can you please explain the steps you have used?

Thanks!
Parvathi.

**Comment by PedalheadPHX** [comment]
In our case we used for the public CoMMpass releases (Salmon | 0.7.2).

Index:
`salmon index
     -t Homo_sapiens_number_fix.GRCh37.74.gtf.hs37d5.EGFRvIII.fa
     -p 12
     --type quasi
     -i Homo_sapiens_number_fix.GRCh37.74.gtf.hs37d5.EGFRvIII_v7.2.fa.index`

For data generation:
`${SALMON_BINARY_v0.7.2} quant \
        --index ${SALMON_INDEX_GTF} \
        --libType ${RNATYPE} \
        --numBootstraps 100 \
        --mates1 <(zcat ${FORWARD}) \
        --mates2 <(zcat ${REVERSE}) \
        --threads 14 \
        --geneMap ${GTF} \
        --output ${SAMPLE}.salmonDir/ensembl74_GTF_V7.2`

For our current approaches please see (https://github.com/tgen/jetstream_resources) for index creation and (https://github.com/tgen/phoenix) for processing code.

**Comment by parvathisudha** [comment]
Hi,
Thanks for the reply. 
So, in that case you just used the transcriptome.fa, right? 
Did you include the GTF file there? I can see that there is .GTF(Homo_sapiens_number_fix.GRCh37.74.gtf) in the transciptome.fa file. Got confused with the file name.
